version: '3.8'
services:

    stonks-ui:
        build:
            context: ./ui
            dockerfile: Dockerfile
        ports: 
            - "4200:80" 
        depends_on:
            - stonks-server
        volumes:
            - ./ui/nginx.conf:/etc/nginx/conf.d/default.conf

    stonks-db:
        image: mongo:4.2
        env_file:
            - ./.env
        volumes:
            - "./mongo/db:/data/db"
            - "./mongo/seed:/seed"
            - "./mongo/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
            - "./mongo/dump/:/dump/"
        ports: 
            - "27017:27017"

    stonks-server:
        build: server
        env_file:
            - ./.env
        volumes:
            - "./logs:/var/log/reddit_momentum"
        ports:
            - "8000:8000"
        links:
            - stonks-db
        depends_on:
            - stonks-db
        restart: always

    scraper:
        build: scraper
        env_file:
            - ./.env
        volumes:
            - "./logs:/var/log/"
        links:
            - stonks-db
        depends_on:
            - stonks-db
